"""initial schema

Revision ID: 37836aab4070
Revises: 
Create Date: 2026-09-22 22:40:11.052839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37836aab4070'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MEMBERS',
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('PRODUCTS',
    sa.Column('product_code', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('tax_category', sa.String(length=10), server_default='standard', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_code')
    )
    op.create_table('STAFF',
    sa.Column('staff_id', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='staff', nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('TAX_RATES',
    sa.Column('tax_rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tax_category', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('tax_rate_id')
    )
    op.create_index(op.f('ix_TAX_RATES_tax_category'), 'TAX_RATES', ['tax_category'], unique=False)
    op.create_table('DISCOUNTS',
    sa.Column('discount_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=False),
    sa.Column('discount_type', sa.Enum('rate', 'amount', name='discount_type_enum'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_code'], ['PRODUCTS.product_code'], ),
    sa.PrimaryKeyConstraint('discount_id')
    )
    op.create_index(op.f('ix_DISCOUNTS_product_code'), 'DISCOUNTS', ['product_code'], unique=False)
    op.create_table('PRODUCT_PRICE_HISTORY',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=False),
    sa.Column('price_before', sa.Integer(), nullable=False),
    sa.Column('price_after', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_code'], ['PRODUCTS.product_code'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_PRODUCT_PRICE_HISTORY_product_code'), 'PRODUCT_PRICE_HISTORY', ['product_code'], unique=False)
    op.create_table('REFRESH_TOKENS',
    sa.Column('token_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['STAFF.staff_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_REFRESH_TOKENS_staff_id'), 'REFRESH_TOKENS', ['staff_id'], unique=False)
    op.create_index(op.f('ix_REFRESH_TOKENS_token_hash'), 'REFRESH_TOKENS', ['token_hash'], unique=False)
    op.create_table('TRANSACTIONS',
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('transaction_datetime', sa.DateTime(), nullable=False),
    sa.Column('staff_id', sa.String(length=20), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=True),
    sa.Column('total_amount_incl_tax', sa.Integer(), nullable=False),
    sa.Column('total_amount_excl_tax', sa.Integer(), nullable=False),
    sa.Column('tax_rate_applied', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['MEMBERS.member_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['STAFF.staff_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_TRANSACTIONS_member_id'), 'TRANSACTIONS', ['member_id'], unique=False)
    op.create_index(op.f('ix_TRANSACTIONS_staff_id'), 'TRANSACTIONS', ['staff_id'], unique=False)
    op.create_table('TRANSACTION_ITEMS',
    sa.Column('transaction_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('unit_price_snapshot', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount_snapshot', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['discount_id'], ['DISCOUNTS.discount_id'], ),
    sa.ForeignKeyConstraint(['product_code'], ['PRODUCTS.product_code'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['TRANSACTIONS.transaction_id'], ),
    sa.PrimaryKeyConstraint('transaction_item_id')
    )
    op.create_index(op.f('ix_TRANSACTION_ITEMS_product_code'), 'TRANSACTION_ITEMS', ['product_code'], unique=False)
    op.create_index(op.f('ix_TRANSACTION_ITEMS_transaction_id'), 'TRANSACTION_ITEMS', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TRANSACTION_ITEMS_transaction_id'), table_name='TRANSACTION_ITEMS')
    op.drop_index(op.f('ix_TRANSACTION_ITEMS_product_code'), table_name='TRANSACTION_ITEMS')
    op.drop_table('TRANSACTION_ITEMS')
    op.drop_index(op.f('ix_TRANSACTIONS_staff_id'), table_name='TRANSACTIONS')
    op.drop_index(op.f('ix_TRANSACTIONS_member_id'), table_name='TRANSACTIONS')
    op.drop_table('TRANSACTIONS')
    op.drop_index(op.f('ix_REFRESH_TOKENS_token_hash'), table_name='REFRESH_TOKENS')
    op.drop_index(op.f('ix_REFRESH_TOKENS_staff_id'), table_name='REFRESH_TOKENS')
    op.drop_table('REFRESH_TOKENS')
    op.drop_index(op.f('ix_PRODUCT_PRICE_HISTORY_product_code'), table_name='PRODUCT_PRICE_HISTORY')
    op.drop_table('PRODUCT_PRICE_HISTORY')
    op.drop_index(op.f('ix_DISCOUNTS_product_code'), table_name='DISCOUNTS')
    op.drop_table('DISCOUNTS')
    op.drop_index(op.f('ix_TAX_RATES_tax_category'), table_name='TAX_RATES')
    op.drop_table('TAX_RATES')
    op.drop_table('STAFF')
    op.drop_table('PRODUCTS')
    op.drop_table('MEMBERS')
    # ### end Alembic commands ###
